#cloud-config
packages:
  - docker
  - docker-compose
  - curl
runcmd:
  - apt install docker
  - apt install docker-compose-plugin
  - curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - apt install docker
  - apt install docker-compose-plugin
  - systemctl start docker
  - systemctl enable docker
