name: Docker deploy on ec2

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: |
        docker build -t webpoint-app -f ./web-app/Dockerfile .
        docker tag webpoint-app:latest ${{secrets.DOCKER_USER}}/webpoint-app:latest
        docker push ${{secrets.DOCKER_USER}}/webpoint-app
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: /home/ubuntu/
        script: |
          cd /home/ubuntu
          docker-compose down
          docker-compose up
